apiVersion: v1
kind: Service
metadata:
  name: postgresql-db-headless
  namespace: kubeestatehub
  labels:
    app: postgresql-db
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: kubeestatehub
spec:
  clusterIP: None
  selector:
    app: postgresql-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
